### Ejercicio 1 
Una startup instala paneles solares en tres barrios (A, B y C) durante 6 meses. Vamos a analizar la información de producción y costos. 

**A. Simulación y armado del DataFrame**

a. Generar con NumPy dos arrays 6x3 (6 meses y 3 barrios):

   i.   energia = energía producida (en MWh)

   ii.  costo_unitario = costo por MWh

b.  Armar un DataFrame con columnas: mes, A, B, C (para energía) y costo_A, costo_B y costo_C

c.  Agregar columna de costo total mensual y fila de costo total por barrio


In [5]:
import numpy as np
import pandas as pd

# Establecer semilla para reproducibilidad
np.random.seed(42)

# a. Generar arrays 6x3 (6 meses, 3 barrios)

# i. Energía producida (en MWh) - valores entre 50 y 200 MWh
energia = np.random.uniform(50, 200, size=(6, 3))

# ii. Costo unitario por MWh - valores entre 80 y 120 USD/MWh
costo_unitario = np.random.uniform(80, 120, size=(6, 3))

print("Energía producida (MWh):")
print(energia)
print("\nCosto unitario (USD/MWh):")
print(costo_unitario)

Energía producida (MWh):
[[106.18101783 192.60714596 159.79909127]
 [139.79877263  73.40279607  73.39917805]
 [ 58.71254183 179.92642187 140.16725176]
 [156.21088667  53.08767414 195.48647782]
 [174.86639612  81.8508666   77.27374508]
 [ 77.51067648  95.63633644 128.71346474]]

Costo unitario (USD/MWh):
[[ 97.27780075  91.64916561 104.47411579]
 [ 85.57975443  91.68578594  94.65447373]
 [ 98.24279937 111.40703846  87.98695129]
 [100.56937754 103.69658275  81.85801651]
 [104.30179408  86.82096495  82.60206372]
 [117.95542149 118.62528132 112.33589392]]
